deploy/urls.py
from django.urls import path
from .views import *


app_name = "deploy"
urlpatterns = [
    path('project/tags', ProjectTagsView.as_view(), name='tags'),
    path('job/build', JobCreateView.as_view(), name='job_build'),
    path('job/add', JobCreateView.as_view(), name='job_add'),
    path('job/list', JobListView.as_view(), name='job_list'),
    path('job_plan/add/job/<int:job_id>', JobPlanCreateView.as_view(), name='job_plan_add'),
    path('job/update/<int:pk>', JobUpdateView.as_view(), name='job_update'),
    path('job/detail/<int:pk>', JobDetailView.as_view(), name='job_detail'),
    path('job/delete/<int:pk>', JobDeleteView.as_view(), name='job_delete'),
    path('job_plan/list/<int:job_id>', JobPlanListView.as_view(), name='job_plan_list'),
    path('job_plan/detail/<int:pk>', JobPlanDetailView.as_view(), name='job_plan_detail'),
    path('job_plan/update/<int:pk>', JobPlanUpdateView.as_view(), name='job_plan_update'),
    path('job/progress', GetAllJobsProgress.as_view(), name='get_all_jobs_process'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sys_mgr/', include('sys_mgr.urls')),
    path('ticket/', include('ticket.urls')),
    path('deploy/', include('deploy.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticket/urls.py
from django.urls import path
from .views import *

app_name = "ticket"
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('add', TicketCreateView.as_view(), name='create'),
    path('add/from/<int:ticket_id>/to/<str:space_code>', TicketCreateFromTicketView.as_view(), name='create_from_ticket'),
    path('bind', ticket_bind_info, name='bind'),
    path('list', TicketListView.as_view(), name='list'),
    path('tome', TicketToMeListView.as_view(), name='to_me_list'),
    path('detail/<int:pk>', TicketDetailView.as_view(), name='detail'),
    path('update/<int:pk>', TicketUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', TicketDeleteView.as_view(), name='delete'),
    path('cancel/<int:pk>', TicketCancelUpdateView.as_view(), name='cancel'),
    path('audit/<int:pk>', TicketAuditUpdateView.as_view(), name='audit'),
    path('execute/<int:pk>', TicketExecuteUpdateView.as_view(), name='execute'),
    path('test/<int:pk>', TicketTestUpdateView.as_view(), name='test'),
]

deploy/models.py
from django.db import models
from .constant import *


class Project(models.Model):
	name = models.CharField(max_length=64, verbose_name='项目名')
	description = models.CharField(max_length=256, verbose_name='项目说明', blank=True, null=True)
	repository = models.OneToOneField("Repository", verbose_name="版本仓库", on_delete=models.CASCADE,
	                                  related_name='project', blank=True, null=True)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = u"项目"
		verbose_name_plural = verbose_name


class Service(models.Model):
	name = models.CharField(max_length=64, verbose_name='服务名')
	description = models.CharField(max_length=256, verbose_name='服务说明', blank=True, null=True)
	project = models.ForeignKey("Project", verbose_name="项目", on_delete=models.CASCADE, related_name='services')

	def __str__(self):
		return "{0}({1})".format(self.name, self.project.name)

	class Meta:
		verbose_name = u"服务"
		verbose_name_plural = verbose_name


class Repository(models.Model):
	name = models.CharField(max_length=64, verbose_name='仓库名')
	description = models.CharField(max_length=256, verbose_name='仓库说明', blank=True, null=True)
	vcs_project_id = models.IntegerField(verbose_name='版本项目ID', blank=True, null=True)
	vcs_type = models.SmallIntegerField(choices=REPOSITORY_TYPE, verbose_name='版本库类型')
	vcs_url = models.CharField(max_length=512, verbose_name='版本库地址', blank=True, null=True)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = u"仓库"
		verbose_name_plural = verbose_name


class JenkinsJob(models.Model):
	service = models.ForeignKey("Service", verbose_name="服务", on_delete=models.CASCADE, related_name='jenkins_jobs')
	space = models.ForeignKey('sys_mgr.Space', verbose_name="空间", on_delete=models.CASCADE, related_name='jenkins_jobs')
	job_name = models.CharField("Jenkins-Job", max_length=256, null=False, blank=False, default="")

	def __str__(self):
		return "[{0}]-[{1}]-[{2}]".format(self.space,self.service,self.job_name)

	class Meta:
		verbose_name = u"Jenkins-Job"
		verbose_name_plural = verbose_name


class Job(models.Model):
	name = models.CharField("发布名", max_length=256, null=False, blank=False, default="")
	description = models.TextField("发布描述", blank=True, null=True)
	service = models.ForeignKey("Service", verbose_name="服务", on_delete=models.CASCADE, related_name='jobs')
	create_user = models.ForeignKey('sys_mgr.User', verbose_name="创建用户", on_delete=models.CASCADE, related_name='jobs',blank=True ,null=True)
	space = models.ForeignKey('sys_mgr.Space', verbose_name="空间", on_delete=models.CASCADE, related_name='jobs')
	status = models.SmallIntegerField("状态", blank=True, default=0)

	def __str__(self):
		return self.name

	def get_status_name(self):
		if self.status == 0:
			return "空闲"
		elif self.status == 1:
			return "构建中"
		return "未知"

	class Meta:
		verbose_name = u"发布"
		verbose_name_plural = verbose_name


class JobPlan(models.Model):
	name = models.CharField("发布计划名", max_length=64, unique=True)
	job = models.ForeignKey("Job", verbose_name="发布", on_delete=models.CASCADE, related_name='job_plans')
	ticket = models.ForeignKey("ticket.Ticket", verbose_name="关联工单", on_delete=models.CASCADE,
	                           related_name='job_plans', blank=True, null=True)
	vcs_tag = models.CharField("分支或标签", max_length=256, blank=True, null=True)
	execute_user = models.ForeignKey("sys_mgr.User", verbose_name="执行人员", on_delete=models.CASCADE,
	                                 related_name='job_plans', blank=True, null=True)
	job_type = models.SmallIntegerField("发布方式", choices=JOB_TYPE, blank=True, default=0)
	created_type = models.SmallIntegerField("创建类型", choices=CREATED_TYPE, blank=True, default=0)
	duration = models.IntegerField("构建时长", default=0, blank=True, null=True)
	jenkins_build_number = models.IntegerField("jenkins构建号", blank=True, null=True)
	#jenkins_job = models.ForeignKey("JenkinsJob", verbose_name="jenkins构建Job对象", blank=True, null=True)
	status = models.SmallIntegerField("结果", blank=True, default=0)
	detail_description = models.TextField("发布计划详情", blank=True, null=True)
	console_output = models.TextField("发布console信息", blank=True, null=True)
	finished_at = models.DateTimeField("完成时间", blank=True, null=True)
	created_at = models.DateTimeField("创建时间", auto_now_add=True)

	def __str__(self):
		return self.name

	def get_job_type_name(self):
		job_type = ''
		for k, v in JOB_TYPE:
			if k == self.job_type:
				job_type = v
		return job_type

	def get_created_type_name(self):
		created_type = ''
		for k, v in CREATED_TYPE:
			if k == self.created_type:
				created_type = v
		return created_type

	def get_status_name(self):
		if self.status == 0:
			return "构建中"
		elif self.status == 1:
			return "成功"
		elif self.status == 2:
			return "失败"
		return "未知"

	class Meta:
		verbose_name = u"发布计划"
		verbose_name_plural = verbose_name

deploy/views.py
from django.views import View
from django.views.generic import ListView, CreateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy
from django.http import JsonResponse, Http404
from django.shortcuts import reverse, redirect, HttpResponse, get_object_or_404
from django.utils import timezone

from apscheduler.schedulers.background import BackgroundScheduler
from django_apscheduler.jobstores import DjangoJobStore, register_events, register_job

import time
import json
import _thread
import urllib.request

from .utils import *
from .forms import *
from .models import *
from sys_mgr.utils import get_user
from mysite.settings import GIT_HOST, GIT_PRIVATE_TOKEN


class ProjectTagsView(View):
    def get(self, request):
        """
        获取GIT标签版本
        """
        service_id = request.GET.get('service_id')
        try:
            service = Service.objects.get(id=service_id)
        except Exception as e:
            print(e)
            service = None
        if not service:
            return JsonResponse({'errno': -1, 'errmsg': 'id error', 'data': {}}, safe=False)
        git_host = GIT_HOST
        private_token = GIT_PRIVATE_TOKEN
        project_id = service.project.repository.vcs_project_id
        response = urllib.request.urlopen(
            url="http://{0}/api/v4/projects/{1}/repository/tags?private_token={2}".format(git_host,project_id,
                                                                                          private_token))
        reps = response.read().decode("utf-8")
        tags_json = json.loads(reps)
        tags_list = []
        for tag in tags_json[:30]:
            tags_list.append('refs/tags/'+tag['name'])

        response = urllib.request.urlopen(
            url="http://{0}/api/v4/projects/{1}/repository/branches?private_token={2}".format(git_host, project_id,
                                                                                          private_token))
        reps = response.read().decode("utf-8")
        print(reps)
        branches_json = json.loads(reps)
        branches_list = []
        for branch in branches_json[:30]:
            branches_list.append('*/' + branch['name'])
        return JsonResponse({'errno': 0, 'errmsg': 'ok', 'data': tags_list+branches_list}, safe=False)


class GetAllJobsProgress(View):
    def get(self, request):
        jobs_data_list = []
        for job in Job.objects.all():
            #通过状态判断jobplan是否执行，如果没有执行则直接构造列表
            if job.status == 0:
                jobs_data_list.append({'job_id': job.id, 'progress': 100})
            else:
                #获取最新job_plan的创建时间
                last_job_plan = job.job_plans.order_by('-created_at')[0]
                print(timezone.now(), last_job_plan.created_at)
                last_job_plan_duration_seconds = (timezone.now() - last_job_plan.created_at).total_seconds()
                job_plans_queryset = job.job_plans.order_by('-finished_at')[:2]
                if job_plans_queryset.count() == 2:
                    total_seconds = 0
                    for job_plan in job_plans_queryset:
                        total_seconds += job_plan.duration/1000.0
                    average_seconds = total_seconds / 2
                    average_seconds = 60 if average_seconds == 0 else average_seconds
                    estimate_progress = last_job_plan_duration_seconds / average_seconds * 0.8 * 100
                else:
                    estimate_progress = last_job_plan_duration_seconds * 0.8
                progress = 95 if estimate_progress > 95 else estimate_progress
                jobs_data_list.append({'job_id': job.id, 'progress': progress})
            #如果在执行，获取最近2次的该job的构建时间取平均值，否则执行时间，通过执行的秒数*5并且如果结果大于95，设置值为95
        return JsonResponse({'errno': 0, 'errmsg': 'ok', 'data': jobs_data_list}, safe=False)


def job_plan_build_job():
    pass

class JobCreateView(CreateView):
    form_class = JobForm
    template_name = 'deploy/job_form.html'
    success_url = '/deploy/job/list'

    def form_valid(self, form):
        form.instance.create_user = get_user(self.request)
        return super(JobCreateView, self).form_valid(form)

    def form_invalid(self, form):
        return HttpResponse("form is invalid.. this is just an HttpResponse object")


class JobPlanCreateView(CreateView):
    form_class = JobPlanForm
    template_name = 'deploy/job_plan_form.html'
    success_url = '/deploy/job/list'

    def dispatch(self, request, *args, **kwargs):
        """
         获取job_id得到job对象
        """
        try:
            job = get_object_or_404(Job, pk=kwargs['job_id'])
            self.job = job
            self.name = job.name
        except:
            pass
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        #生成job_plan对象
        super(JobPlanCreateView, self).post(request)
        #调用jenkins接口执行升级
        try:
            job_space = self.object.job.space
            job_service = self.object.job.service
            jenkins_job = JenkinsJob.objects.get(space=job_space, service=job_service)
            job_name = jenkins_job.job_name
            next_build_number = get_next_build_number(job_space, job_name)
            build_job_branch_tag(job_space, job_name, self.object.vcs_tag)
            # 设置job 的状态为构建中
            self.object.jenkins_build_number = next_build_number
            self.object.save()
            self.object.job.status = 1
            self.object.job.save()
            _thread.start_new_thread(self.update_job_plan, (job_space, job_name))
            message = "发布中"
        except Exception as e:
            message = "发布异常"
        return redirect(reverse("deploy:job_list"))

    def update_job_plan(self, space, job_name):
        # 设置job默认为失败
        _start_count = 0
        while _start_count < 180:
            job_build_result = get_job_build_result(space, job_name, self.object.jenkins_build_number)
            if job_build_result == 'SUCCESS':
                self.object.status = 1
                break
            elif job_build_result == 'FAILURE':
                self.object.status = 2
                break
            time.sleep(1)
            _start_count += 1

        if _start_count >= 180:
            return
        # 更新job_plan的状态
        self.object.finished_at = timezone.now()
        duration = get_job_build_info(space, job_name, self.object.jenkins_build_number)['duration']
        self.object.duration = duration if duration != 0 else 22
        self.object.console_output = get_job_build_console_output(space, job_name, self.object.jenkins_build_number)
        self.object.save()
        if self.object.ticket:
            print("准备保存ticket")
            self.object.ticket.execute_update()
            self.object.ticket.save()
        # 更新job的状态
        self.object.job.status = 0
        self.object.job.save()

    def get_initial(self, *args, **kwargs):
        initial = super(JobPlanCreateView, self).get_initial(**kwargs)
        datetime_string = timezone.now().strftime('%Y%m%d%H%M%S')
        initial['name'] = "{0}-{1}".format(self.job.name, datetime_string)
        initial['job'] = self.job
        initial['job_type'] = 1
        initial['created_type'] = 1
        initial['project'] = self.job.service.project
        initial['service'] = self.job.service
        return initial

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        form = super(JobPlanCreateView, self).get_form(form_class)
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['job'] = self.job
        return context

    def form_valid(self, form):
        form.instance.execute_user = get_user(self.request)
        form.instance.status = 0
        form.instance.created_at = timezone.now()
        return super(JobPlanCreateView, self).form_valid(form)

    def form_invalid(self, form):
        return HttpResponse("form is invalid.. this is just an HttpResponse object")


class JobListView(ListView):
    model = Job
    context_object_name = 'jobs'
    template_name = "deploy/job_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_user'] = get_user(self.request)
        return context


class JobPlanListView(ListView):
    model = JobPlan
    context_object_name = 'job_plans'
    template_name = "deploy/job_plan_list.html"

    def get_queryset(self):
        try:
            job = get_object_or_404(Job, pk=self.kwargs['job_id'])
            self.job = job
            queryset = JobPlan.objects.filter(job=job)
        except:
            queryset = JobPlan.objects.all()
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['job'] = self.job
        return context


class JobDetailView(DetailView):
    model = Job


class JobPlanDetailView(DetailView):
    model = JobPlan
    template_name = 'deploy/job_plan_detail.html'


class JobUpdateView(UpdateView):
    model = Job
    form_class = JobUpdateForm
    template_name = 'deploy/job_form.html'
    success_url = reverse_lazy('deploy:job_list')

    def form_invalid(self, form):
        print("error:" + str(form.errors))
        return HttpResponse("form is invalid.. this is just an HttpResponse object")


class JobDeleteView(DeleteView):
    model = Job
    success_url = reverse_lazy('deploy:job_list')

    def get_object(self, queryset=None):
        obj = super(JobDeleteView, self).get_object()
        if not obj.create_user == get_user(self.request):
            raise Http404
        return obj


class JobPlanUpdateView(UpdateView):
    model = Job
    form_class = JobPlanUpdateForm
    template_name = 'deploy/ticket_form.html'

deploy/templates/deploy/job_confirm_delete.html
{% extends "base.html" %}
{% load static %}
{% block title %}删除发布{% endblock %}
{% block content_header_page1 %}主页{% endblock %}
{% block content_header_page2 %}删除发布{% endblock %}
{% block content %}
  <div class="container-fluid">
    <div class="row">
      <!-- left column -->
      <div class="col-md-8">
        <!-- general form elements -->
        <div class="card card-danger">
          <div class="card-header">
            <h3 class="card-title">{% block card_title %}删除发布{% endblock %}</h3>
          </div>
          <!-- /.card-header -->
          {% block form %}
          <!-- form start -->
            <div class="card-body">
                <form action="" method="post" role="form" >
                    {% csrf_token %}
                    <p>确认要删除发布 "{{ object }}" 吗?</p>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-danger" value="Submit" >确认</button>
                    </div>
                </form>
            </div>
          {% endblock %}
        </div>
      </div>
    </div>
  </div>
    <!-- /.card -->
{% endblock %}

deploy/templates/deploy/job_form.html
{% extends "form.html" %}
{% load static %}
{% block title %}发布管理{% endblock %}
{% block content_header %}发布管理{% endblock %}
{% block content_header_page1 %}主页{% endblock %}
{% block content_header_page2 %}发布管理{% endblock %}
{% block card_title %}发布管理{% endblock %}
{% block card_title_component %}&nbsp;<button type="button" class="btn btn-success btn-sm"><ion-icon name="person-add"></ion-icon> 新增</button>{% endblock %}
{% block form %}
    <!-- form start -->
    <form method="post" role="form" action="">
        {% csrf_token %}
        <div class="card-body">
            <div class="form-group">
                <label class="control-label col-xs-1" for="title">{{ form.name.label }}:</label>
                {{ form.name }}
            </div>
            <div class="form-group">
                <label class="control-label col-xs-1" for="title">{{ form.description.label }}:</label>
                {{ form.description }}
            </div>
            <div class="form-group">
                <label class="control-label col-xs-1" for="title">{{ form.service.label }}:</label>
                {{ form.service }}
            </div>
             <div class="form-group">
                <label class="control-label col-xs-1" for="space">{{ form.space.label }}:</label>
                {{ form.space }}
            </div>
            <div class="form-group" style="display: none">
                {{ form.status }}
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary" value="Submit" id="submit" >提交</button>
        </div>
    </form>
{% endblock %}

{% block base_script %}
    {{ block.super }}
    <script>
        $("#submit").click(function(){
            $("#id_space").attr("disabled",false);
        });
    </script>
{% endblock %}

deploy/templates/deploy/job_operator_btn.html
{% if btn_type == 'job_plan_add' %}
<a class="btn btn-dark btn-sm" href="#" style="display: {% if job.status == 1 %} display {% else %} none {% endif %}"
   data="{% url "deploy:job_plan_add" job.id %}" id="id_build_btn_{{ job.id }}">
    <ion-icon name="build"></ion-icon> 构建</a>

    <a class="btn btn-primary btn-sm" href="{% url "deploy:job_plan_add" job.id %}"
   style="display: {% if job.status != 1 %} display {% else %} none {% endif %}" id="id_build_active_btn_{{ job.id }}">
    <ion-icon name="build"></ion-icon> 构建</a>

{% elif btn_type == 'job_history' %}
    <a class="btn btn-info btn-sm" href="{% url "deploy:job_plan_list" job.id %}">
        <ion-icon name="recording"></ion-icon> 发布历史</a>
{% elif btn_type == 'job_update' %}
    <a class="btn btn-success btn-sm" href="{% url "deploy:job_update" job.id %}">
        <ion-icon name="create"></ion-icon> 更新</a>
{% elif btn_type == 'job_delete' %}
    <a class="btn btn-danger btn-sm" href="{% url "deploy:job_delete" job.id %}" style="display: none">
        <ion-icon name="close-circle"></ion-icon> 删除</a>
{% elif btn_type == 'audit' %}
    <a class="btn btn-primary btn-sm" href="{% url "deploy:audit" deploy.id %}">审核</a>
{% elif btn_type == 'execute' %}
    <a class="btn btn-primary btn-sm" href="{% url "deploy:execute" deploy.id %}">发布</a>
{% elif btn_type == 'test' %}
    <a class="btn btn-primary btn-sm" href="{% url "deploy:test" deploy.id %}">测试</a>
{% endif %}

deploy/templates/deploy/job_plan_form.html
{% extends "form.html" %}
{% load static %}
{% block title %}发布计划管理{% endblock %}
{% block content_header %}发布计划管理{% endblock %}
{% block content_header_page1 %}主页{% endblock %}
{% block content_header_page2 %}发布计划管理{% endblock %}
{% block card_title %}发布计划管理{% endblock %}
{% block card_title_component %}&nbsp;<button type="button" class="btn btn-success btn-sm"><ion-icon name="person-add"></ion-icon> 新增</button>{% endblock %}
{% block form %}
    <!-- form start -->
    <form method="post" role="form" action="">
        {% csrf_token %}
        <div class="card-body">
            <div class="form-group">
                <label class="control-label col-xs-1" for="title">{{ form.name.label }}:</label>
                {{ form.name }}
            </div>
            <div class="form-group">
                <label class="control-label col-xs-1" for="title">{{ form.project.label }}:</label>
                {{ form.project }}
            </div>
            <div class="form-group">
                <label class="control-label col-xs-1" for="title">{{ form.service.label }}:</label>
                {{ form.service }}
            </div>
            <div class="form-group">
                <label class="control-label col-xs-1" for="title">{{ form.job.label }}:</label>
                {{ form.job }}
            </div>
            <div class="form-group">
                <label class="control-label col-xs-1" for="title">{{ form.job_type.label }}:</label>
                {{ form.job_type }}
            </div>
            <div class="form-group">
                <label class="control-label col-xs-1" for="title">{{ form.created_type.label }}:</label>
                {{ form.created_type }}
            </div>
            <div class="form-group">
                <label class="control-label col-xs-1" for="title">{{ form.vcs_tag.label }}:</label>
                {{ form.vcs_tag }}
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary" value="Submit" id="submit" >构建</button>
        </div>
    </form>
{% endblock %}

{% block base_script %}
    {{ block.super }}
    <script>
        $(function (){
            $.ajax({
                url: "/deploy/project/tags?service_id="+{{job.service.id}},
                dataType : "json",
                type: "get",
                success: function(data){
                   $("#id_vcs_tag option").remove();
                   if(data.errno ==0 ){
                       for(var i=0; i<data.data.length;i++){
                           if(i == 0 ){
                               $('#id_vcs_tag').append('<option value="'+data.data[i]+'" selected="selected">'+data.data[i]+'</option>');
                           }else{
                               $('#id_vcs_tag').append('<option value="'+data.data[i]+'">'+data.data[i]+'</option>');
                           }
                       }
                   }
                }
            });
        });
        $("#submit").click(function(){
            $("#id_name").attr("disabled",false);
            $("#id_job").attr("disabled",false);
            $("#id_job_type").attr("disabled",false);
            $("#id_created_type").attr("disabled",false);
        });
    </script>
{% endblock %}

deploy/templates/deploy/job_plan_operator_btn.html
{% if btn_type == 'job_plan_detail' %}
    <a class="btn btn-primary btn-sm" href="{% url "deploy:job_plan_detail" job_plan.id %}"><ion-icon name="information-circle"></ion-icon> 详情</a>
{% elif btn_type == 'job_history' %}
    <a class="btn btn-info btn-sm" href="{% url "deploy:job_plan_list" job_plan.id %}"><ion-icon name="recording"></ion-icon> 历史记录</a>
{% elif btn_type == 'job_update' %}
    <a class="btn btn-success btn-sm" href="{% url "deploy:job_update" job_plan.id %}"><ion-icon name="create"></ion-icon> 更新</a>
{% elif btn_type == 'job_delete' %}
    <a class="btn btn-danger btn-sm" href="{% url "deploy:job_delete" job_plan.id %}"><ion-icon name="close-circle"></ion-icon> 删除</a>
{% elif btn_type == 'audit' %}
    <a class="btn btn-primary btn-sm" href="{% url "deploy:audit" job_plan.id %}">审核</a>
{% elif btn_type == 'execute' %}
    <a class="btn btn-primary btn-sm" href="{% url "deploy:execute" job_plan.id %}">发布</a>
{% elif btn_type == 'test' %}
    <a class="btn btn-primary btn-sm" href="{% url "deploy:test" job_plan.id %}">测试</a>
{% endif %}

deploy/templates/deploy/job_plan_status_btn.html
{% if job_plan.status == 0 %}
    <button class="btn btn-primary btn-sm"><ion-icon name="reload-circle"></ion-icon>{{ job_plan.get_status_name }}</button>
{% elif job_plan.status == 1 %}
    <button class="btn btn-success btn-sm"><ion-icon name="checkmark-circle"></ion-icon>{{ job_plan.get_status_name }}</button>
{% elif job_plan.status == 2 %}
    <button class="btn btn-danger btn-sm"><ion-icon name="alert-circle"></ion-icon>{{ job_plan.get_status_name }}</button>
{% endif %}

deploy/templates/deploy/job_plan_table.html
{% if table_type == 'table_header' %}
    <th>发布计划名</th>
    <th>发布</th>
    <th>关联工单</th>
    <th>标签或分支</th>
    <th>执行用户</th>
    <th>发布类型</th>
    <th>创建方式</th>
    <th>创建时间</th>
    <th>完成时间</th>
    <th>状态</th>
    <th>操作</th>
{% elif  table_type == 'table_body' %}
    <td>{{ job_plan.name }} <i class="fas fa-copy copy swalDefaultSuccess" style="cursor: pointer;"
 data-clipboard-text='{{ job_plan.name }}'></i></td>
    <td>{{ job_plan.job }}</td>
    <td>
    {% if job_plan.ticket %}
        <a href="{% url "ticket:detail" job_plan.ticket.id %}">{{ job_plan.ticket }}</a>
    {% else %}
        /
    {% endif %}
    </td>
    <td>{{ job_plan.vcs_tag }}</td>
    <td>{{ job_plan.execute_user }}</td>
    <td>{{ job_plan.get_job_type_name }}</td>
    <td>{{ job_plan.get_created_type_name }}</td>
    <td>{{ job_plan.created_at |date:"Y-m-d H:i:s"}}</td>
    <td>{{ job_plan.finished_at |date:"Y-m-d H:i:s"}}</td>
{% endif %}

deploy/templates/deploy/job_table.html
{% if table_type == 'table_header' %}
    <th>发布名</th>
    <th>空间</th>
    <th>服务名</th>
    <th>状态</th>
    <th>操作</th>
{% elif  table_type == 'table_body' %}
    <td>{{ job.name }}</td>
    <td>{{ job.space }}</td>
    <td>{{ job.service }}</td>
{% endif %}