deploy/urls.py
from django.urls import path
from .views import *


app_name = "deploy"
urlpatterns = [
    path('project/tags', ProjectTagsView.as_view(), name='tags'),
    path('job/build', JobCreateView.as_view(), name='job_build'),
    path('job/add', JobCreateView.as_view(), name='job_add'),
    path('job/list', JobListView.as_view(), name='job_list'),
    path('job_plan/add/job/<int:job_id>', JobPlanCreateView.as_view(), name='job_plan_add'),
    path('job/update/<int:pk>', JobUpdateView.as_view(), name='job_update'),
    path('job/detail/<int:pk>', JobDetailView.as_view(), name='job_detail'),
    path('job/delete/<int:pk>', JobDeleteView.as_view(), name='job_delete'),
    path('job_plan/list/<int:job_id>', JobPlanListView.as_view(), name='job_plan_list'),
    path('job_plan/detail/<int:pk>', JobPlanDetailView.as_view(), name='job_plan_detail'),
    path('job_plan/update/<int:pk>', JobPlanUpdateView.as_view(), name='job_plan_update'),
    path('job/progress', GetAllJobsProgress.as_view(), name='get_all_jobs_process'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sys_mgr/', include('sys_mgr.urls')),
    path('ticket/', include('ticket.urls')),
    path('deploy/', include('deploy.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sys_mgr/urls.py
from django.urls import path
from .views import IndexView, UserListView, RoleListView, PermissionListView, MenuListView, SpaceListView, LoginView

app_name = "sys_mgr"
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('login', LoginView.as_view(), name='login'),
    path('user', UserListView.as_view(), name='user'),
    path('role', RoleListView.as_view(), name='role'),
    path('permission', PermissionListView.as_view(), name='permission'),
    path('menu', MenuListView.as_view(), name='menu'),
    path('space', SpaceListView.as_view(), name='space'),
    path('ticket/add', IndexView.as_view(), name='ticket'),
    path('ticket/list', IndexView.as_view(), name='ticket'),
    path('ticket/audit/list', IndexView.as_view(), name='ticket'),
    path('ticket/task/list', IndexView.as_view(), name='ticket'),
]

sys_mgr/models.py
from django.db import models


class User(models.Model):
	username = models.CharField(max_length=64, unique=True)
	chinese_name = models.CharField(max_length=64,blank=True,null=True, verbose_name="中文名")
	password = models.CharField(max_length=128)
	roles = models.ManyToManyField("Role")
	spaces = models.ManyToManyField("Space")
	position = models.ManyToManyField("Position", verbose_name="职位")
	status = models.SmallIntegerField()
	created_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.chinese_name if self.chinese_name else self.username

	def get_perm_url_list(self):
		_perm_url_list=[]
		for role in self.roles.all():
			for permission in role.permissions.all():
				_perm_url_list.append(permission.url)
		return _perm_url_list

	class Meta:
		verbose_name = u"用户"
		verbose_name_plural = verbose_name


class Department(models.Model):
	name = models.CharField(max_length=64, verbose_name="部门名", unique=True)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = u"部门"
		verbose_name_plural = verbose_name


class Position(models.Model):
	name = models.CharField(max_length=64, verbose_name="职位名称", unique=True)
	department = models.ForeignKey("Department", verbose_name="部门", on_delete=models.CASCADE)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = u"职位"
		verbose_name_plural = verbose_name


class Role(models.Model):
	name = models.CharField(max_length=64)
	permissions = models.ManyToManyField("Permission")

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = u"角色"
		verbose_name_plural = verbose_name


class Permission(models.Model):
	name = models.CharField(max_length=64)
	url = models.CharField(max_length=200, null=True, blank=True)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = u"权限"
		verbose_name_plural = verbose_name


class Menu(models.Model):
	name = models.CharField(max_length=64)
	url = models.CharField(max_length=128, null=True, blank=True)
	parent_menu = models.ForeignKey("Menu", null=True, blank=True, on_delete=models.CASCADE)
	icon_name = models.CharField(max_length=32, default='circle')
	seq = models.IntegerField()

	def __str__(self):
		if self.parent_menu is not None:
			return "[ "+self.parent_menu.name+" ]->"+"[ "+self.name+" ]"
		return "[ "+self.name+" ]"

	class Meta:
		verbose_name = u"菜单"
		verbose_name_plural = verbose_name


class Space(models.Model):
	name = models.CharField(max_length=64)
	code = models.CharField(max_length=64, unique=False, default="")

	def __str__(self):
		return "{0}({1})".format(self.name,self.code)

	class Meta:
		verbose_name = u"空间"
		verbose_name_plural = verbose_name

sys_mgr/views.py
from django.shortcuts import HttpResponse, render, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from django.views import View
from .models import *
import re

class LoginRequiredMixin(object):
    @classmethod
    def as_view(cls, **init_kwargs):
        view = super(LoginRequiredMixin, cls).as_view(**init_kwargs)
        return login_required(view)


class LoginView(View):
    def get(self, request):
        return render(request, 'login.html')

    def post(self, request):
        username = request.POST.get("username")
        password = request.POST.get("password")
        #判断数据库中是否存在
        try:
            user = User.objects.get(username=username)
        except:
            user = None
        if user:
            if password == user.password:
                request.session['user_id'] = user.id
                _perm_url_list = user.get_perm_url_list()
                request.session['perm_url_list'] = _perm_url_list
                submenu_obj_list = []
                for menu in Menu.objects.filter(parent_menu__isnull=False):
                    for perm_url in _perm_url_list:
                        if re.match("^"+perm_url+"$", menu.url):
                            submenu_obj_list.append(menu)
                menu_list = {}
                for submenu in submenu_obj_list:
                    if submenu.parent_menu.name in menu_list.keys():
                        exist_submenu_list = menu_list[submenu.parent_menu.name]
                        exist_submenu_list.append({"name": submenu.name, "url": submenu.url})
                    else:
                        menu_list[submenu.parent_menu.name] = [{"name": submenu.name, "url": submenu.url}]
                request.session['menu_list'] = menu_list
                return render(request, 'index2.html')
        return render(request, 'login.html', {'message': "账号不存在或密码错误!!!"})


class IndexView(View):
    def get(self, request):
        return render(request, 'index.html')


class UserListView(ListView):
    model = User
    context_object_name = 'users'
    template_name = "user.html"


class RoleListView(ListView):
    model = Role
    context_object_name = 'roles'
    template_name = "role.html"


class PermissionListView(ListView):
    model = Permission
    context_object_name = 'permissions'
    template_name = "permission.html"


class MenuListView(ListView):
    model = Menu
    context_object_name = 'menus'
    template_name = "menu.html"


class SpaceListView(ListView):
    model = Space
    context_object_name = 'spaces'
    template_name = "space.html"

sys_mgr/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block title %} Admin TL {% endblock %}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  {% block base_css %}
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static "sys_mgr/plugins/fontawesome-free/css/all.min.css"  %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet" href="{% static "sys_mgr/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css"  %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static "sys_mgr/plugins/icheck-bootstrap/icheck-bootstrap.min.css"  %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static "sys_mgr/plugins/jqvmap/jqvmap.min.css"  %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static "sys_mgr/dist/css/adminlte.min.css"  %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static "sys_mgr/plugins/overlayScrollbars/css/OverlayScrollbars.min.css"  %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static "sys_mgr/plugins/daterangepicker/daterangepicker.css"  %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static "sys_mgr/plugins/summernote/summernote-bs4.css"  %}">
    <!-- SweetAlert2 -->
  <link rel="stylesheet" href="{% static "sys_mgr/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css"  %}">
  <!-- Toastr -->
  <link rel="stylesheet" href="{% static "sys_mgr//plugins/toastr/toastr.min.css"  %}">
  {% endblock %}

</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Navbar -->
  {% block navbar %}
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>
  {% endblock %}
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  {% block sidebar %}
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">Alexander Pierce</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
        {% load web %}
        {% get_menu_styles request %}
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>
  {% endblock %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">{% block content_header %}base Content Header{% endblock %}</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">{% block content_header_page1 %}主页{% endblock %}</a></li>
              <li class="breadcrumb-item active">{% block content_header_page2 %}base{% endblock %}</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      {% block content %}
      base content
      {% endblock %}
      {% block modal %}
      {% endblock %}
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  {% block footer %}
  <footer class="main-footer">
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">树童运维平台</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.0.4
    </div>
  </footer>
  {% endblock %}

  <!-- Control Sidebar -->
  {% block control_siderbar %}
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  {% endblock %}
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

{% block base_script %}
<!-- jQuery -->
<script src="{% static "sys_mgr/plugins/jquery/jquery.min.js"  %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static "sys_mgr/plugins/jquery-ui/jquery-ui.min.js"  %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static "sys_mgr/plugins/bootstrap/js/bootstrap.bundle.min.js"  %}"></script>
<!-- ChartJS -->
<script src="{% static "sys_mgr/plugins/chart.js/Chart.min.js"  %}"></script>
<!-- Sparkline -->
<script src="{% static "sys_mgr/plugins/sparklines/sparkline.js"  %}"></script>
<!-- JQVMap -->
<script src="{% static "sys_mgr/plugins/jqvmap/jquery.vmap.min.js"  %}"></script>
<script src="{% static "sys_mgr/plugins/jqvmap/maps/jquery.vmap.usa.js"  %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static "sys_mgr/plugins/jquery-knob/jquery.knob.min.js"  %}"></script>
<!-- daterangepicker -->
<script src="{% static "sys_mgr/plugins/moment/moment.min.js"  %}"></script>
<script src="{% static "sys_mgr/plugins/daterangepicker/daterangepicker.js"  %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static "sys_mgr/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"  %}"></script>
<!-- Summernote -->
<script src="{% static "sys_mgr/plugins/summernote/summernote-bs4.min.js"  %}"></script>
<!-- overlayScrollbars -->
<script src="{% static "sys_mgr/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"  %}"></script>
<!-- AdminLTE App -->
<script src="{% static "sys_mgr/dist/js/adminlte.js"  %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static "sys_mgr/dist/js/pages/dashboard.js"  %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static "sys_mgr/dist/js/demo.js"  %}"></script>

<script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>
<script src="https://cdn.bootcss.com/clipboard.js/1.7.1/clipboard.js"></script>

{% endblock %}
</body>
</html>

sys_mgr/templates/form.html
{% extends "base.html" %}
{% load static %}
{% block title %}表单模板{% endblock %}
{% block content_header_page1 %}主页{% endblock %}
{% block content_header_page2 %}表单模板{% endblock %}
{% block content %}
  <div class="container-fluid">
    <div class="row">
      <!-- left column -->
      <div class="col-md-8">
        <!-- general form elements -->
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">{% block card_title %}表单模板{% endblock %}</h3>
          </div>
          <!-- /.card-header -->
          {% block form %}
          <!-- form start -->
            <div class="card-body">
                <form method="post" role="form">
                {% csrf_token %}
                {{ form.as_p }}
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary" value="Submit" >提交</button>
                    </div>
                </form>
            </div>
          {% endblock %}
        </div>
      </div>
    </div>
  </div>
        <!-- /.card -->
{% endblock %}

sys_mgr/templates/index2.html
{% extends "base.html" %}
{% block base_css %}
    {{ block.super }}
{% endblock %}
{% block title %}主页{% endblock %}
{% block content_header_page1 %}主页{% endblock %}
{% block content_header_page2 %}页面{% endblock %}
{% block content %}主页内容{% endblock %}
{% block base_script %}
    {{ block.super }}
{% endblock %}

sys_mgr/templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Sys_mgr</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static "sys_mgr/plugins/fontawesome-free/css/all.min.css"  %}">
  <!-- Ionicons -->
  <!--
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  -->
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static "sys_mgr/plugins/icheck-bootstrap/icheck-bootstrap.min.css"  %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static "sys_mgr/dist/css/adminlte.min.css"  %}">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <b>树童运维管理平台</b>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg"></p>

      <form action="{%  url "sys_mgr:login" %}" method="post">
          {% csrf_token %}
          {{ message }}
        <div class="input-group mb-3">
          <input type="username" name="username" class="form-control" placeholder="用户名">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" name="password" class="form-control" placeholder="密码">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="remember">
              <label for="remember">
                记住我
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">登录</button>
          </div>
          <!-- /.col -->
        </div>
      </form>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{% static "sys_mgr/plugins/jquery/jquery.min.js"  %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static "sys_mgr/plugins/bootstrap/js/bootstrap.bundle.js"  %}"></script>
<!-- AdminLTE App -->
<script src="{% static "sys_mgr/dist/js/adminlte.min.js"  %}"></script>

</body>
</html>

sys_mgr/templates/login2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <span style="color:red">{{ message }}</span>
    <form action="/sys_mgr/login" method="post">
        {% csrf_token %}
        用户名：<input type="text" name="username"><br>
        密码：<input type="text" name="password"><br>
        <input type="submit" id="submit" name="submit" value="Login" />
    </form>
</body>
</html>

sys_mgr/templates/menu.html
{% extends "table.html" %}
{% load static %}
{% block title %}菜单管理{% endblock %}
{% block content_header %}菜单管理{% endblock %}
{% block content_header_page1 %}主页{% endblock %}
{% block content_header_page2 %}菜单管理{% endblock %}
{% block card_title %}菜单管理{% endblock %}
{% block card_title_component %}&nbsp;<button type="button" class="btn btn-success btn-sm"><ion-icon name="person-add"></ion-icon> 新增</button>{% endblock %}
{% block card_body %}
  <table id="example2" class="table table-bordered table-hover">
    <thead>
    <tr>
      <th>角色名</th>
      <th></th>
      <th>权限</th>
      <th>操作</th>
    </tr>
    </thead>
    <tbody>
    {% for menu in menus %}
    <tr>
        <td>{{ menu.name }}</td>
        <td>{{ menu.url }}</td>
        <td>
            <button type="button" class="btn btn-primary btn-sm"><ion-icon name="information-circle"></ion-icon> 详情</button>
            <button type="button" class="btn btn-success btn-sm"><ion-icon name="create"></ion-icon> 编辑</button>
            <button type="button" class="btn btn-danger btn-sm"><ion-icon name="trash"></ion-icon> 删除</button>
        </td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock %}

sys_mgr/templates/menu_bak.html
<div class="static-menu">

    {% for menu,submenu_list in menu_list.items %}
        {{ menu }}<br>
        {% for sub_menu in submenu_list %}
            <a href="{{ sub_menu.url }}">
                --{{ sub_menu.name }}
            </a><br>
        {% endfor %}
    {% endfor %}

</div>

sys_mgr/templates/permission.html
{% extends "table.html" %}
{% load static %}
{% block title %}权限管理{% endblock %}
{% block content_header %}权限管理{% endblock %}
{% block content_header_page1 %}主页{% endblock %}
{% block content_header_page2 %}权限管理{% endblock %}
{% block card_title %}权限管理{% endblock %}
{% block card_title_component %}&nbsp;<button type="button" class="btn btn-success btn-sm"><ion-icon name="person-add"></ion-icon> 新增</button>{% endblock %}
{% block card_body %}
  <table id="example2" class="table table-bordered table-hover">
    <thead>
    <tr>
      <th>权限名</th>
      <th>URL</th>
      <th>操作</th>
    </tr>
    </thead>
    <tbody>
    {% for permission in permissions %}
    <tr>
        <td>{{ permission.name }}</td>
        <td>{{ permission.url }}</td>
        <td>
            <button type="button" class="btn btn-primary btn-sm"><ion-icon name="information-circle"></ion-icon> 详情</button>
            <button type="button" class="btn btn-success btn-sm"><ion-icon name="create"></ion-icon> 编辑</button>
            <button type="button" class="btn btn-danger btn-sm"><ion-icon name="trash"></ion-icon> 删除</button>
        </td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock %}