deploy/urls.py
from django.urls import path
from .views import *


app_name = "deploy"
urlpatterns = [
    path('project/tags', ProjectTagsView.as_view(), name='tags'),
    path('job/build', JobCreateView.as_view(), name='job_build'),
    path('job/add', JobCreateView.as_view(), name='job_add'),
    path('job/list', JobListView.as_view(), name='job_list'),
    path('job_plan/add/job/<int:job_id>', JobPlanCreateView.as_view(), name='job_plan_add'),
    path('job/update/<int:pk>', JobUpdateView.as_view(), name='job_update'),
    path('job/detail/<int:pk>', JobDetailView.as_view(), name='job_detail'),
    path('job/delete/<int:pk>', JobDeleteView.as_view(), name='job_delete'),
    path('job_plan/list/<int:job_id>', JobPlanListView.as_view(), name='job_plan_list'),
    path('job_plan/detail/<int:pk>', JobPlanDetailView.as_view(), name='job_plan_detail'),
    path('job_plan/update/<int:pk>', JobPlanUpdateView.as_view(), name='job_plan_update'),
    path('job/progress', GetAllJobsProgress.as_view(), name='get_all_jobs_process'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sys_mgr/', include('sys_mgr.urls')),
    path('ticket/', include('ticket.urls')),
    path('deploy/', include('deploy.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticket/urls.py
from django.urls import path
from .views import *

app_name = "ticket"
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('add', TicketCreateView.as_view(), name='create'),
    path('add/from/<int:ticket_id>/to/<str:space_code>', TicketCreateFromTicketView.as_view(), name='create_from_ticket'),
    path('bind', ticket_bind_info, name='bind'),
    path('list', TicketListView.as_view(), name='list'),
    path('tome', TicketToMeListView.as_view(), name='to_me_list'),
    path('detail/<int:pk>', TicketDetailView.as_view(), name='detail'),
    path('update/<int:pk>', TicketUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', TicketDeleteView.as_view(), name='delete'),
    path('cancel/<int:pk>', TicketCancelUpdateView.as_view(), name='cancel'),
    path('audit/<int:pk>', TicketAuditUpdateView.as_view(), name='audit'),
    path('execute/<int:pk>', TicketExecuteUpdateView.as_view(), name='execute'),
    path('test/<int:pk>', TicketTestUpdateView.as_view(), name='test'),
]

ticket/models.py
from django.db import models
from deploy.models import Project
from sys_mgr.models import User,Space
from django.utils import timezone

class TicketType(models.Model):
	name = models.CharField("类型名", max_length=256)
	code = models.CharField("代码", max_length=64, blank=True, null=True)
	description = models.TextField("类型描述",  blank=True, null=True)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = u"工单类型"
		verbose_name_plural = verbose_name


class TicketBindInfo(models.Model):
	type = models.ForeignKey('TicketType', verbose_name="工单类型", on_delete=models.CASCADE,
	                         related_name='ticket_bind_info', blank=True, null=True)
	space = models.ForeignKey('sys_mgr.Space', verbose_name="空间", on_delete=models.CASCADE,
	                          related_name='ticket_bind_info_space')
	service = models.ForeignKey('deploy.Service', verbose_name="服务名", on_delete=models.CASCADE)
	audit_user = models.ForeignKey("sys_mgr.User", verbose_name="审核人员", on_delete=models.CASCADE,
	                               related_name='ticket_bind_info_audit_user', blank=True, null=True)
	execute_user = models.ForeignKey("sys_mgr.User", verbose_name="执行人员", on_delete=models.CASCADE,
	                                 related_name='ticket_bind_info_execute_user', blank=True, null=True)
	test_user = models.ForeignKey("sys_mgr.User", verbose_name="测试人员", on_delete=models.CASCADE,
	                              related_name='ticket_bind_info_test_user', blank=True, null=True)

	def __str__(self):
		return "{0}-{1}-{2}-{3}-{4}".format(self.type,self.space,self.service,self.audit_user,self.execute_user,self.test_user)

	class Meta:
		verbose_name = u"工单绑定信息"
		verbose_name_plural = verbose_name


class Ticket(models.Model):
	number = models.CharField(max_length=64, verbose_name='工单编号', null=True, blank=True)
	type = models.ForeignKey('TicketType', verbose_name="工单类型", on_delete=models.CASCADE, related_name='tickets', blank=True, null=True)
	parent = models.ForeignKey('self', verbose_name="父工单", on_delete=models.CASCADE, related_name='sub_tickets', blank=True, null=True)
	title = models.CharField("说明", max_length=256, null=False, blank=False, default="")
	space = models.ForeignKey('sys_mgr.Space', verbose_name="空间", on_delete=models.CASCADE, related_name='tickets_space')
	service = models.ForeignKey('deploy.Service', verbose_name="服务名", on_delete=models.CASCADE, default=None)
	vcs_tag = models.CharField("分支或标签", max_length=256,blank=True, null=True)
	test_user = models.ForeignKey("sys_mgr.User", verbose_name="测试人员", on_delete=models.CASCADE, related_name='tickets_test_user', blank=True, null=True)
	test_description = models.TextField("测试备注",  blank=True, null=True)
	audit_user = models.ForeignKey("sys_mgr.User", verbose_name="审核人员", on_delete=models.CASCADE, related_name='tickets_audit_user', blank=True, null=True)
	audit_description = models.TextField("审核意见", blank=True, null=True)
	execute_user = models.ForeignKey("sys_mgr.User", verbose_name="执行人员", on_delete=models.CASCADE, related_name='tickets_execute_user')
	execute_description = models.TextField("发布备注", blank=True, null=True)
	cancel_description = models.TextField("作废说明", blank=True, null=True)
	create_user = models.ForeignKey("sys_mgr.User", verbose_name="创建人员", on_delete=models.CASCADE, related_name='tickets_create_user', blank=True, null=True)
	service_conf = models.TextField("服务配置",  blank=True, null=True)
	db_conf = models.TextField("数据库配置",  blank=True, null=True)
	db_file = models.FileField(upload_to='sql/%Y/%m/%d/', verbose_name="数据库文件",  blank=True, null=True)
	other_conf = models.TextField("其他配置", blank=True, null=True)
	status = models.SmallIntegerField("状态", blank=True, default=0)
	tested_at = models.DateTimeField("测试时间", blank=True, null=True)
	audited_at = models.DateTimeField("审核时间", blank=True, null=True)
	executed_at = models.DateTimeField("执行时间", blank=True, null=True)
	finished_at = models.DateTimeField("完成时间", blank=True, null=True)
	created_at = models.DateTimeField("创建时间", auto_now_add=True)

	def __str__(self):
		return "{0}({1})".format(self.title,self.number)

	def is_need_audit(self):
		return True if self.audit_user else False

	def is_need_test(self):
		return True if self.test_user else False

	def audit_approved(self):
		return True if self.status == 11 else False

	def test_approved(self):
		return True if self.status == 31 else False

	def create_update_info(self):
		if self.audit_user:
			self.status = 10
		else:
			self.status = 20
		self.save()

	def audit_update_info(self):
		if self.status == 11:
			self.status = 20
		self.audited_at = timezone.now()
		self.save()

	def execute_update_info(self):
		self.executed_at = timezone.now()
		if self.test_user:
			self.status = 30
		else:
			self.status = 40
			self.finished_at = timezone.now()
		self.save()




	class Meta:
		verbose_name = u"工单"
		verbose_name_plural = verbose_name

ticket/views.py
from django.views.generic import ListView, CreateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy
from django.http import Http404, JsonResponse
from django.views import View
from django.shortcuts import reverse, render, redirect, HttpResponse, get_object_or_404

from .forms import *
from .models import *
from django.db.models import Q
from datetime import datetime
from sys_mgr.utils import get_user
from django.utils import timezone

from deploy.models import Job, JobPlan, JenkinsJob
from deploy.utils import *
import json


# Create your views here.
class IndexView(View):
    def get(self, request):
        return render(request, 'index.html')


def ticket_bind_info(request):
    type_id = request.GET.get('type_id')
    space_id = request.GET.get('space_id')
    service_id = request.GET.get('service_id')
    ticket_bind_info = TicketBindInfo.objects.filter(type__id=type_id, space__id=space_id, service__id=service_id).first()
    print("ticket_bind_info:{0}".format(ticket_bind_info))
    #判断工单是否有做人员绑定
    if not ticket_bind_info:
        audit_users_list = []
        execute_users_list = []
        test_users_list = []
        try:
            space = Space.objects.get(id=space_id)
        except:
            space = None
        if space and space.code == 'TEST':
            robot = User.objects.get(username='robot')
            execute_users_list.append({'execute_user_id': robot.id,
                                       'execute_user_name': robot.chinese_name})
            is_bind = 1
        else:
            audit_users = User.objects.filter(position__name="审核人员")
            execute_users = User.objects.filter(position__name="运维人员")
            test_users = User.objects.filter(position__name="测试人员")

            for audit_user in audit_users:
                audit_users_list.append({'audit_user_id': audit_user.id, 'audit_user_name': audit_user.chinese_name})
            for execute_user in execute_users:
                execute_users_list.append({'execute_user_id': execute_user.id,
                                           'execute_user_name': execute_user.chinese_name})
            for test_user in test_users:
                test_users_list.append({'test_user_id': test_user.id, 'test_user_name': test_user.chinese_name})
            is_bind = 0

        data = {'bind': is_bind, 'audit_users_list': audit_users_list, 'execute_users_list': execute_users_list,
                'test_users_list': test_users_list}
    else:
        audit_users_list = []
        execute_users_list = []
        test_users_list = []

        if ticket_bind_info.audit_user:
            audit_users_list.append({'audit_user_id': ticket_bind_info.audit_user.id,
                                     'audit_user_name': ticket_bind_info.audit_user.chinese_name})

        if ticket_bind_info.execute_user:
            execute_users_list.append({'execute_user_id': ticket_bind_info.execute_user.id,
                                     'execute_user_name': ticket_bind_info.execute_user.chinese_name})

        if ticket_bind_info.test_user:
            test_users_list.append({'test_user_id': ticket_bind_info.test_user.id,
                                     'test_user_name': ticket_bind_info.test_user.chinese_name})
        data = {'bind': 1, 'audit_users_list': audit_users_list, 'execute_users_list': execute_users_list,
                    'test_users_list': test_users_list}
    return JsonResponse({'errno': 0, 'errmsg': 'ok', 'data': data}, safe=False)


def create_job_plan(ticket):
    space = ticket.space
    service = ticket.service
    job = Job.objects.get(space=space, service=service)
    jenkins_job = JenkinsJob.objects.get(space=space, service=service)
    datetime_string = timezone.now().strftime('%Y%m%d%H%M%S')
    job_plan_name = "{0}-{1}".format(job.name, datetime_string)
    job_name = jenkins_job.job_name
    next_build_number = get_next_build_number(space, job_name)
    job_plan = JobPlan(name=job_plan_name, job=job, ticket=ticket, vcs_tag=ticket.vcs_tag,
                       execute_user=ticket.execute_user, job_type=2, created_type=2,
                       jenkins_build_number=next_build_number)
    build_job_branch_tag(space, job_name, ticket.vcs_tag)
    # 设置job 的状态为构建中
    job_plan.save()
    job_plan.job.status = 1
    job_plan.job.save()


def create_job_plan_by_robot(ticket):
    if ticket.execute_user.username == 'robot':
        create_job_plan(ticket)


def create_job_plan_by_user(ticket):
    create_job_plan(ticket)


class TicketCreateView(CreateView):
    form_class = TicketForm
    template_name = 'ticket/ticket_form.html'
    success_url = '/ticket/list'

    def post(self, request, *args, **kwargs):
        super(TicketCreateView, self).post(request)
        try:
            if not self.object.is_need_audit():
                create_job_plan_by_robot(self.object)
        except Exception as e:
            print(e)
        return redirect(reverse("ticket:list"))

    def get_initial(self, *args, **kwargs):
        initial = super(TicketCreateView, self).get_initial(**kwargs)
        try:
            ticket_type = TicketType.objects.get(code="BUSINESS_SERVICE")
            space = Space.objects.get(code="TEST")
            initial['type'] = ticket_type
            initial['space'] = space
        except:
            pass
        return initial

    def form_valid(self, form):
        form.instance.create_user = get_user(self.request)
        form.instance.create_update_info()
        datetime_string = timezone.now().strftime('%Y%m%d%H%M%S%f')
        if form.instance.type.name == '数据库':
            form.instance.number = 'SD'+datetime_string
        elif form.instance.type.name == '业务服务':
            form.instance.number = 'SY' + datetime_string
        elif form.instance.type.name == '中间件':
            form.instance.number = 'SM' + datetime_string
        else:
            form.instance.number = 'SO' + datetime_string
        return super(TicketCreateView, self).form_valid(form)

    def form_invalid(self, form):
        return HttpResponse("form is invalid.. this is just an HttpResponse object")


class TicketCreateFromTicketView(CreateView):
    form_class = TicketFromTicketForm
    template_name = 'ticket/ticket_add_from_ticket_form.html'
    success_url = '/ticket/list'

    def post(self, request, *args, **kwargs):
        super(TicketCreateFromTicketView, self).post(request)
        try:
            if not self.object.is_need_audit():
                create_job_plan_by_robot(self.object)
        except Exception as e:
            print(e)
        return redirect(reverse("ticket:list"))

    def get_initial(self, *args, **kwargs):
        initial = super(TicketCreateFromTicketView, self).get_initial(**kwargs)
        print("get_initial")
        try:
            ticket_id = self.kwargs['ticket_id']
            space_code = self.kwargs['space_code']
            try:
                ticket = Ticket.objects.get(pk=ticket_id)
            except:
                ticket = None

            try:
                space = Space.objects.get(code=space_code)
            except:
                space = Space.objects.get(code="TEST")
            if ticket and space.code != 'TEST':
                ticket_type = ticket.type
                parent = ticket
                title = "[{0}]{1}".format(space.name, ticket.title)
                service = ticket.service
                vcs_tag = ticket.vcs_tag
                service_conf = ticket.service_conf
                db_conf = ticket.db_conf
                db_file = ticket.db_file
                other_conf = ticket.db_conf
                initial['type'] = ticket_type
                initial['parent'] = parent
                initial['title'] = title
                initial['space'] = space
                initial['service'] = service
                initial['vcs_tag'] = vcs_tag
                initial['service_conf'] = service_conf
                initial['db_conf'] = db_conf
                initial['db_file'] = db_file
                initial['other_conf'] = other_conf
        except Exception as e:
            print(e)
        return initial

    def form_valid(self, form):
        form.instance.create_user = get_user(self.request)
        form.instance.create_update_info()
        datetime_string = timezone.now().strftime('%Y%m%d%H%M%S%f')
        if form.instance.type.name == '数据库':
            form.instance.number = 'SD' + datetime_string
        elif form.instance.type.name == '业务服务':
            form.instance.number = 'SY' + datetime_string
        elif form.instance.type.name == '中间件':
            form.instance.number = 'SM' + datetime_string
        else:
            form.instance.number = 'SO' + datetime_string
        return super(TicketCreateFromTicketView, self).form_valid(form)

    def form_invalid(self, form):
        return HttpResponse("form is invalid.. this is just an HttpResponse object")


class TicketDeleteView(DeleteView):
    model = Ticket
    success_url = reverse_lazy('ticket:to_me_list')

    def get_object(self, queryset=None):
        obj = super(TicketDeleteView, self).get_object()
        if not obj.create_user == get_user(self.request):
            raise Http404
        return obj


class TicketUpdateView(UpdateView):
    model = Ticket
    form_class = TicketUpdateForm
    template_name = 'ticket/ticket_form.html'
    success_url = reverse_lazy('ticket:to_me_list')

    def form_valid(self, form):
        form.instance.create_user = get_user(self.request)
        form.instance.create_update_info()
        return super(TicketUpdateView, self).form_valid(form)

    def form_invalid(self, form):
        print("error:" + str(form.errors))
        return HttpResponse("form is invalid.. this is just an HttpResponse object")


class TicketCancelUpdateView(UpdateView):
    model = Ticket
    form_class = TicketCancelForm

ticket/templates/ticket/clearable_file_input.html
{% if widget.is_initial %}{{ widget.initial_text }}: <a href="{{ widget.value.url }}">{{ widget.value }}</a>{% if not widget.required %}
<div class="custom-control custom-checkbox">
<input type="checkbox" class="custom-control-input" name="{{ widget.checkbox_name }}" id="{{ widget.checkbox_id }}">
<label for="{{ widget.checkbox_id }}" class="custom-control-label">{{ widget.clear_checkbox_label }}</label>{% endif %}<br>
</div>
<label class="control-label col-xs-1" for="customFile">{{ widget.input_text }}:</label>
{% endif %}
<div class="custom-file">
<input type="{{ widget.type }}" class="custom-file-input" name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %}>
<label class="custom-file-label" for="customFile" >
</label>
</div>

ticket/templates/ticket/ticket_bak.html
<td>{{ ticket.type }}</td>
        <td>{{ ticket.title }}</td>
        <td>{{ ticket.space }}</td>
        <td>{{ ticket.project }}</td>
        <td>{{ ticket.vcs_tag }}</td>
        <td>{% if ticket.audit_user %}
                {{ ticket.audit_user.chinese_name }}
                {% if ticket.audited_at %}
                    {% if ticket.status == 12 %}
                        <i class="fas fa-times-circle text-danger"></i>
                    {% else %}
                        <i class="fas fa-check-circle text-success"></i>
                    {% endif %}
                {% else %}
                    <i class="fas fa-clock text-warning"></i>
                {% endif %}
            {% else %}
                /
            {% endif %}
        </td>
        <td>{% if ticket.execute_user %}
                {{ ticket.execute_user.chinese_name }}
                {% if ticket.executed_at %}
                    {% if ticket.status == 22 %}
                        <i class="fas fa-times-circle text-danger"></i>
                    {% else %}
                        <i class="fas fa-check-circle text-success"></i>
                    {% endif %}
                {% else %}
                    <i class="fas fa-clock text-warning"></i>
                {% endif %}
            {% else %}
                /
            {% endif %}
        </td>
        <td>{% if ticket.test_user %}
                {{ ticket.test_user.chinese_name }}
                {% if ticket.tested_at %}
                    {% if ticket.status == 32 %}
                        <i class="fas fa-times-circle text-danger"></i>
                    {% else %}
                        <i class="fas fa-check-circle text-success"></i>
                    {% endif %}
                {% else %}
                    <i class="fas fa-clock text-warning"></i>
                {% endif %}
            {% else %}
                /
            {% endif %}
        </td>

ticket/templates/ticket/ticket_execute_form.html
{% extends "form.html" %}
{% load static %}
{% block title %}工单管理{% endblock %}
{% block content_header %}工单管理{% endblock %}
{% block content_header_page1 %}主页{% endblock %}
{% block content_header_page2 %}工单管理{% endblock %}
{% block card_title %}工单管理{% endblock %}
{% block card_title_component %}&nbsp;<button type="button" class="btn btn-success btn-sm"><ion-icon name="person-add"></ion-icon> 新增</button>{% endblock %}
{% block form %}
    <!-- form start -->
    <form method="post" role="form">
        {% csrf_token %}
        <div class="card-body">
            <div class="form-group">
                <label class="control-label col-xs-1" for="type">{{ form.type.label }}:</label>
                {{ form.type }}
            </div>
            <div class="form-group">
                <label class="control-label col-xs-1" for="title">{{ form.title.label }}:</label>
                {{ form.title }}
            </div>
             <div class="form-group">
                <label class="control-label col-xs-1" for="space">{{ form.space.label }}:</label>
                {{ form.space }}
            </div>
            <div class="form-group">
                <label class="control-label col-xs-1" for="project">{{ form.project.label }}:</label>
                {{ form.project }}
            </div>
            <div class="form-group">
                <label class="control-label col-xs-1" for="vcs_tag">{{ form.vcs_tag.label }}:</label>
                {{ form.vcs_tag }}
            </div>
            <div class="form-group">
                <label class="control-label col-xs-1" for="audit_user">{{ form.audit_user.label }}:</label>
                {{ form.audit_user }}
            </div>
            <div class="form-group">
                <label class="control-label col-xs-1" for="execute_user">{{ form.execute_user.label }}:</label>
                {{ form.execute_user }}
            </div>
            <div class="form-group">
                <label class="control-label col-xs-1" for="audit_user">{{ form.test_user.label }}:</label>
                {{ form.test_user }}
            </div>
            <div class="form-group">
                <label class="control-label col-xs-1" for="service_conf">{{ form.service_conf.label }}:</label>
                {{ form.service_conf }}
            </div>
            <div class="form-group">
                <label class="control-label col-xs-1" for="db_conf">{{ form.db_conf.label }}:</label>
                {{ form.db_conf }}
            </div>
            <div class="form-group">
                <label class="control-label col-xs-1" for="other_conf">{{ form.other_conf.label }}:</label>
                {{ form.other_conf }}
            </div>
            <div class="form-group">
                <label class="control-label col-xs-1" for="execute_description">{{ form.execute_description.label }}:</label>
                {{ form.execute_description }}
            </div>
            <div class="form-group" style="display: none">
                {{ form.status }}
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary" value="Submit" id="submit" >提交</button>
        </div>
    </form>
{% endblock %}

{% block base_script %}
    {{block.super}}
    <script>
        $("#submit").click(function(){
            $("#id_type").attr("disabled",false);
            $("#id_title").attr("disabled",false);
            $("#id_space").attr("disabled",false);
            $("#id_service").attr("disabled",false);
            $("#id_vcs_tag").attr("disabled",false);
            $("#id_audit_user").attr("disabled",false);
            $("#id_execute_user").attr("disabled",false);
            $("#id_test_user").attr("disabled",false);
            $("#id_service_conf").attr("disabled",false);
            $("#id_db_conf").attr("disabled",false);
            $("#id_other_conf").attr("disabled",false);
        });

    </script>
{% endblock %}

ticket/templates/ticket/ticket_form.html
{% extends "form.html" %}
{% load static %}
{% block title %}工单管理{% endblock %}
{% block content_header %}工单管理{% endblock %}
{% block content_header_page1 %}主页{% endblock %}
{% block content_header_page2 %}工单管理{% endblock %}
{% block card_title %}工单管理{% endblock %}
{% block card_title_component %}&nbsp;<button type="button" class="btn btn-success btn-sm"><ion-icon name="person-add"></ion-icon> 新增</button>{% endblock %}
{% block form %}
    <!-- form start -->
    <form method="post" role="form" enctype="multipart/form-data" action="">
        {% csrf_token %}
        <div class="card-body">
            <div class="form-group" style="display: none" >
                {{ form.number }}
            </div>
            <div class="form-group">
                <label class="control-label col-xs-1" for="title">{{ form.type.label }}:</label>
                {{ form.type }}
            </div>
            <div class="form-group">
                <label class="control-label col-xs-1" for="title">{{ form.title.label }}:</label>
                {{ form.title }}
            </div>
             <div class="form-group">
                <label class="control-label col-xs-1" for="space">{{ form.space.label }}:</label>
                {{ form.space }}
            </div>
            <div class="form-group">
                <label class="control-label col-xs-1" for="service">{{ form.service.label }}:</label>
                {{ form.service }}
            </div>
            <div class="form-group">
                <label class="control-label col-xs-1" for="vcs_tag">{{ form.vcs_tag.label }}:</label>
                {{ form.vcs_tag }}
            </div>
            <div class="form-group">
                <label class="control-label col-xs-1" for="audit_user">{{ form.audit_user.label }}:</label>
                {{ form.audit_user }}
            </div>
            <div class="form-group">
                <label class="control-label col-xs-1" for="execute_user">{{ form.execute_user.label }}:</label>
                {{ form.execute_user }}
            </div>
            <div class="form-group">
                <label class="control-label col-xs-1" for="audit_user">{{ form.test_user.label }}:</label>
                {{ form.test_user }}
            </div>
            <div class="form-group">
                <label class="control-label col-xs-1" for="service_conf">{{ form.service_conf.label }}:</label>
                {{ form.service_conf }}
            </div>
            <div class="form-group">
                <label class="control-label col-xs-1" for="db_conf">{{ form.db_conf.label }}:</label>
                {{ form.db_conf }}
            </div>
            <div class="form-group">
                <label class="control-label col-xs-1" for="db_file">{{ form.db_file.label }}:</label>
                {{ form.db_file }}
            </div>
            <div class="form-group">
                <label class="control-label col-xs-1" for="other_conf">{{ form.other_conf.label }}:</label>
                {{ form.other_conf }}
            </div>
            <div class="form-group" style="display: none">
                <label class="control-label col-xs-1" for="status">{{ form.status.label }}:</label>
                {{ form.status }}
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary" value="Submit" id="submit" >提交</button>
        </div>
    </form>
{% endblock %}

{% block  base_script %}
    {{ block.super }}
    <script src="{% static "sys_mgr/plugins/bs-custom-file-input/bs-custom-file-input.min.js" %}"></script>
    <script>
        $(document).ready(function () {
          bsCustomFileInput.init();
        });
        $('#id_type').change(function(){
            var ticket_type=$(this).children(":selected").text();
            var service_id=$("#id_service").children(":selected").attr("value");
            if(ticket_type != "业务服务"){
                $("#id_vcs_tag option").remove();
                $("#id_vcs_tag").attr("disabled",true);
            }else{
                $("#id_vcs_tag").attr("disabled",false);
                $.ajax({
                    url: "/deploy/project/tags?service_id="+service_id,
                    dataType : "json",
                    type: "get",
                    success: function(data){
                       $("#id_vcs_tag option").remove();
                       if(data.errno ==0 ){
                           for(var i=0; i<data.data.length;i++){
                               if(i == 0 ){
                                   $('#id_vcs_tag').append('<option value="'+data.data[i]+'" selected="selected">'+data.data[i]+'</option>');
                               }else{
                                   $('#id_vcs_tag').append('<option value="'+data.data[i]+'">'+data.data[i]+'</option>');
                               }
                           }
                       }
                    }
                });
            }
        });
        $('#id_service').change(function(){
            var ticket_type=$('#id_type').children(":selected").text();
            var service_id=$(this).children(":selected").attr("value");
            if(ticket_type == "业务服务"){
                $("#id_vcs_tag").attr("disabled",false);
                $.ajax({
                    url: "/deploy/project/tags?service_id="+service_id,
                    dataType : "json",
                    type: "get",
                    success: function(data){
                       $("#id_vcs_tag option").remove();
                       if(data.errno ==0 ){
                           for(var i=0; i<data.data.length;i++){
                               if(i == 0 ){
                                   $('#id_vcs_tag').append('<option value="'+data.data[i]+'" selected="selected">'+data.data[i]+'</option>');
                               }else{
                                   $('#id_vcs_tag').append('<option value="'+data.data[i]+'">'+data.data[i]+'</option>');
                               }
                           }
                       }
                    }
                });
            }else{
                $("#id_vcs_tag option").remove();
            }
        });
    </script>
    <script>
        $("#submit").click(function(){
            $("#id_type").attr("disabled",false);
            $("#id_title").attr("disabled",false);
            $("#id_space").attr("disabled",false);
            $("#id_service").attr("disabled",false);
            $("#id_vcs_tag").attr("disabled",false);
            $("#id_audit_user").attr("disabled",false);
            $("#id_execute_user").attr("disabled",false);
            $("#id_test_user").attr("disabled",false);
            $("#id_service_conf").attr("disabled",false);
            $("#id_db_conf").attr("disabled",false);
            $("#id_other_conf").attr("disabled",false);
        });
    </script>
{% endblock %}

ticket/templates/ticket/ticket_modal.html
<div class="modal fade" id="modal-xl">
    <div class="modal-dialog modal-xl">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" id="model_title"></h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <text id="modal_content"></text>
        </div>
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->